global:
  marketplace-ami: false
  owner: somckitk@amazon.com
  qsname: quickstart-sap-netweaver-abap
  regions:
    - us-east-1
  reporting: true
tests:
  master:
    template_file: sap-netweaver-abap-master.template
    parameter_input: sap-netweaver-abap-master.json
